baseURL = "https://project-sterrenstof.nl/"
languageCode = "nl-nl"
title = "Project SterrenStof"
theme = "sterrenstof"
[author]
  gravatarEmail = "cmdr@supakeen.com"
  homepageText = "Project SterrenStof"
  name = "supakeen"
  rss = "/weblog/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params]
  description = "A blog about everything."
  licence = "[Some Rights Reserved](http://creativecommons.org/licenses/by-sa/4.0/)."
  displayPostLanguage = false
[permalinks]
  posts = "/weblog/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
